In [2]:
import torch
import numpy as np

### Basic Tensors in Pytorch

In [17]:
#Note : Not tuple like numpy empty,zeros,rand
x = torch.empty(5, 3)
x = torch.zeros(5, 3, dtype=torch.long)
npx = np.zeros((5, 3), dtype=np.float64)
y = torch.tensor([5.6, 6.7])
npy = np.array([5.6, 6.7])
print("x.size():", x.size()) #shape works here too
print("npx.shape:", npx.shape)

x.size(): torch.Size([5, 3])
npx.shape: (5, 3)


### Pytorch supports normal addition as well as torch.add

In [20]:
a = y + y
print(y, a , a.size())
a = torch.add(y, y)

tensor([5.6000, 6.7000]) tensor([11.2000, 13.4000]) torch.Size([2])


### Pytorch View(Equivalent to numpy reshape)

In [21]:
'''View in torch is reshape equivalent in numpy'''
a = a.view(1, 2)
'''-1 implies it is inferred from other arguments'''
a = a.view(-1, 2)
print("a.size():", a.size())

a.size(): torch.Size([1, 2])


### One element tensor to Python value conversion

In [24]:
x = torch.randn(1)
print("x:", x)
print("x.item():", x.item())

x: tensor([0.1315])
x.item(): 0.13151521980762482


### Tensor and Numpy array conversions.
### Tensors and Numpy arrays use same memory locations so changing one would change the other.

In [11]:
#Tensor to numpy
a = torch.rand(5)
b = a.numpy()
print(a, b)

#a = a + 1 #This doesn't change b
a.add_(1) #This changes b
print(a, b)

#Numpy to Tensor
a = np.random.rand(5)
b = torch.from_numpy(a)
print(a, b)

tensor([0.3667, 0.8508, 0.8214, 0.3444, 0.4932]) [0.36672986 0.8508407  0.8214445  0.3443569  0.49324048]
tensor([1.3667, 1.8508, 1.8214, 1.3444, 1.4932]) [1.3667299 1.8508407 1.8214445 1.3443569 1.4932405]
[0.23042243 0.03393089 0.82197046 0.07029039 0.66362785] tensor([0.2304, 0.0339, 0.8220, 0.0703, 0.6636], dtype=torch.float64)


### CUDA Tensors

In [15]:
#Check if CUDA available
print("torch.cuda.is_available():", torch.cuda.is_available())

device = torch.device("cuda")
#Create Tensor Directly on GPU
x = torch.rand(5, device=device)
print("x:", x)
#Move to CPU now
x = x.to("cpu")
print("x:", x)

torch.cuda.is_available(): True
x: tensor([0.5424, 0.2284, 0.3230, 0.9566, 0.5803], device='cuda:0')
x: tensor([0.5424, 0.2284, 0.3230, 0.9566, 0.5803])
