In [2]:
import torch

In [21]:
'''requires_grad needs to be set for Tensor to track computation'''

x = torch.ones(2, 2, requires_grad=True)
#This is used to change grad
x.requires_grad_(False)
x.requires_grad_(True)

#same content but No gradient computed
detx = x.detach()

y = x + 2
#Now y has requires_grad = True
print(y)

z = y * y * 4
print(z)

out = z.mean()
print(out)

out.backward()
print(x.grad)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[36., 36.],
        [36., 36.]], grad_fn=<MulBackward0>)
tensor(36., grad_fn=<MeanBackward0>)
tensor([[6., 6.],
        [6., 6.]])
