In [8]:
import torch
import numpy as np

In [32]:
'''Basic Tensors in Pytorch'''
#Note : Not tuple like numpy empty,zeros,rand
x = torch.empty(5, 3)
x = torch.zeros(5, 3, dtype=torch.long)
npx = np.zeros((5, 3), dtype=np.float64)
y = torch.tensor([5.6, 6.7])
npy = np.array([5.6, 6.7])
print(x.size()) #shape works here too
print(npx.shape)

torch.Size([5, 3])
(5, 3)


In [33]:
'''Pytorch supports normal addition as well torch.add'''
a = y + y
print(y)
print(a)
a = torch.add(y, y)
print(a.size())

tensor([5.6000, 6.7000])
tensor([11.2000, 13.4000])
torch.Size([2])


In [34]:
'''View in torch is reshape equivalent in numpy'''
a = a.view(1, 2)
'''-1 implies it is inferred from other arguments'''
a = a.view(-1, 2)
print(a.size())

torch.Size([1, 2])


In [35]:
'''One element tensor to Python value conversion'''
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0559])
0.055905040353536606


In [57]:
'''
Tensor and Numpy array conversions

Tensors and Numpy arrays use same memory locations so changing one
would change the other

'''

#Tensor to numpy
a = torch.rand(5)
print(a)
b = a.numpy()
print(b)

#a = a + 1 #This doesn't change b
a.add_(1) #This changes b
print(a)
print(b)

#Numpy to Tensor
a = np.random.rand(5)
b = torch.from_numpy(a)
print(a)
print(b)

tensor([0.5527, 0.6367, 0.5108, 0.2761, 0.6883])
[0.55265117 0.63668215 0.51079494 0.27606    0.6882616 ]
tensor([1.5527, 1.6367, 1.5108, 1.2761, 1.6883])
[1.5526512 1.6366822 1.5107949 1.27606   1.6882616]
[0.55785186 0.09553132 0.31082237 0.90870017 0.421873  ]
tensor([0.5579, 0.0955, 0.3108, 0.9087, 0.4219], dtype=torch.float64)


In [62]:
'''CUDA Tensors'''

#Check if available
print(torch.cuda.is_available())

device = torch.device("cuda")

#Create Tensor Directly on GPU
x = torch.rand(5, device=device)
print(x)
#Move to CPU now
x = x.to("cpu")
print(x)

True
tensor([0.5873, 0.9793, 0.1635, 0.4336, 0.5631], device='cuda:0')
tensor([0.5873, 0.9793, 0.1635, 0.4336, 0.5631])
